### PR TITLE
in some cases typeParameters.size > typeArguments.size which leads to…

### PR DESCRIPTION
**Pull request by treblereel**
… IndexOutOfBoundsException

reproducer: https://github.com/treblereel/j2cl-tests/tree/typeArguments

### CODE REVIEW

**Comment by niloc132** [comment]
The reproducer is a bit weird - https://github.com/treblereel/j2cl-tests/blob/typeArguments/src/main/java/org/treblereel/InputSet.java is using raw generics on `Data`, instead of declaring something like `InputSet extends Data<InputSet>` or `InputSet<T> extends Data<T>` - the error is not helpful for a user, but we don't actually want the `Data<T>` to be unbounded do we?

**Comment by treblereel** [comment]
i wouldn't call it 'weird', i prefer 'special' or 'corner' case

**Comment by niloc132** [comment]
In that case, I think the code is wrong - if type args are omitted, then you need to traverse the type _params_ and collect the upper bounds, right?

**Comment by treblereel** [comment]
right, what isn't nice is the fact that this is based on old legacy code i can't fix, but i can use custom handler to marshall it by myself, so feel free to close the issue

**Comment by niloc132** [comment]
No i'm agreeing that shitty cases can exist, but I'm saying that your fix isn't correct for such a case. When the type is raw, we have to use the upper bound of the generic param, since thats what the generic "value" will be when it is raw.

**Comment by vegegoku** [comment]
I have been looking into the reproducer and I have 2 problems with it, first, the index issue can be fixed by providing the type parameters in the field definition.

the second thing is the location of the annotation which is on the field instead of the base class, which is not something domino-jackson can handle.

**Comment by niloc132** [comment]
@vegegoku the bug is that some codebases are dumb and have raw types - at the end of the day it is your project, but I'm not sure that forbidding that is helpful. I do think the _fix_ is wrong (should just notice "its a raw type!" and then use the upper bound correctly), but the use case might happen.

Can't speak to the annotation location bit.

**Pull request closed without merging**
