### PR TITLE
serialize NaN and +/-Infinity as strings in lenient mode

### PR DESCRIPTION
**Pull request by tobias-hammerschmidt**
This is the rebased fix for #68 as stated in https://github.com/DominoKit/domino-jackson/pull/69.

### CODE REVIEW

**Comment by vegegoku** [comment]
For the failed test case it is due to wrong check, when it comes to NaN we cant use `==` or `equals` to do the check like that and instead we can do `Double.isNaN(...)` 
You can read about this here 
https://stackoverflow.com/questions/1456566/how-do-you-test-to-see-if-a-double-is-equal-to-nan
and here 
https://www.baeldung.com/java-not-a-number

The assertion need to be rewritten like this 
```
assertTrue(Double.isNaN(deserialize("NaN")));
```

Would you please update the PR.

**Comment by tobias-hammerschmidt** [comment]
I just pushed the updated test cases as requested.

**Comment by vegegoku** [comment]
There is a missing import in the test cases.

**Comment by vegegoku** [comment]
Also please make sure to run `mvn license:format fmt:format` before you push

**Comment by tobias-hammerschmidt** [comment]
I've added the import and also performed the formatting (with no observable changes).

**Review by vegegoku — APPROVED** [review]

**Pull request merged**
