### PR TITLE
Adding super source folder for jackson-apt

### PR DESCRIPTION
**Pull request by tedynaidenov**
Create "super source" folder for module GwtJacksonApt, containing all source from jackson-super. 
For some environments, jackson-super can do the job by bringing corresponding source/class files from jackson libary, it can not act as full replacement for gwt "super source" folder. For an example building a project, compiled by both javac and gwt compiler and having the jackson library on the class path, can't be done. The <super-source> configuration in the <module_name>.gwt.xml and corresponding sources can do correct replacement of sources for gwt compile.
The proposed idea is far from ideal, I just copied the sources from jackson-super. Probably, something better can be done. But I believe the presence of "super source" folder is a must for this case.

### CODE REVIEW

**Comment by niloc132** [comment]
A gwt2-style super source directory may mess with j2cl, so we do need to be careful there. Note that this should not cause _problems_ in gwt2 client code as long as you keep it in the client classpath, and avoid legacy dev mode (and since the project uses jsinterop, legacy dev mode won't work anyway).

That said, just dumping them in the main directory like this may mess with non-transpiled projects (jvm, android, etc). Do you have a specific failure mode you are seeing with this?

@vegegoku and I have discussed ways to break this into its own gwt-only jar, so that non-gwt jars don't run into problems with it, but haven't taken action yet.

**Comment by tedynaidenov** [comment]
@niloc132 good point, I haven't consider possible interference with j2cl...

The problem I am experiencing, is due to a conflict on the classpath for the UI code: both jackson-annotations.jar and jackson-super.jar are there. The reason for having jackson-annotations , is a transitive dependency via another code/project, which is shared by UI and server. 

I agree that in theory tailoring the classpath for UI code can prevent such kind of problems. Still in practice, this can be hard to do. Maybe the right way to go in GWT only jar, just as you proposed.

**Comment by vegegoku** [comment]
@tedynaidenov @niloc132 Sorry for being late on this.
this topic have been bothering me for sometime, i wanted a good practice to follow to provide super sourcing that works nicely for both GWT and j2cl.
so let me explain what i did with domino-rest, which has the use case as domino-jackson

so domino-rest has 5 modules in total 

- **domino-rest-apt** : the annotation processor
- **domino-rest-shared** : the API
- **domino-rest-gwt** : implementation for gwt
- **domino-rest-server** : implementation for jvm
- **jaxrs-super** : the super sources for jax-rs classes used by domino-rest

what i did differently in domino-rest is : 
-  split the implementation of client/jvm each in its own modules and each has its own dependencies, which means that for using domino-rest in gwt/j2cl world you will need a different dependency than when using it in the jvm.

- in domino-rest-shared the jaxrs-super is a provided dependency (which is think could be replaced with the actual jaxrs dependency)

- domino-rest-server depends on domino-rest-shared and does not include a dependency for jaxrs or a direct dependency on jaxrs-super, so the jax-rs dependency should be provided by the application.

- domino-rest-gwt depends directly on jaxrs-super to make the code compiles for gwt/j2cl

in an application that is clearly split into client/shared/server i think this will prevent jaxrs-super from leaking into the server implementation and prevent the class-path collision. i did a quick test and even when the actual jax-rs dependency was added to the application shared module i had no issue compiling both sides client and server.

but i am not sure if this will worked for an application that mix the client/shared/server class-path.

but so far this is the best i could come up with. and i am really glad to have more brains on this.

**Comment by tedynaidenov** [comment]
@vegegoku Thanks for detailed explanation and suggestions. My case is very similar to domio-rest. There are a plenty of modules, which can be grouped in 3 categories:

- server-side, most of modules here have direct dependencies on API modules

- API (i.e. shared code)

- UI (or gwt), modules here depend on the API modules

Few of the API or shared modules have direct dependency on jackson-annotations. When compiling API modules along with server-side modules, there are no issues. But when trying to compile UI modules, things go wrong. Classpath is created in similar way for both UI and servers-side modules and include all dependencies.For UI modules we have dependencies for both: jackson-super and API modules (latter means transitive dependency on jackson-annotations). And that is the way I end-up with jackson-super and jackson-annotations on the classpath. 

Now I realized that the issues is in my "garden". While gwt super source helps to mitigate the problem, we need to address it by tailoring the classpath in a better way. 

@vegegoku @niloc132 thanks for you comments and suggestions, I will close the pull request.

**Pull request closed without merging**
